### ISSUE TITLE
Chat UI React Component

### ISSUE THREAD

**Issue by mukeshmk** [mukeshmk/chat-app#1]
Create a React Component(s) for the chat application.

This is how I roughly envision the UI to look:

![chat-ui](https://user-images.githubusercontent.com/7903100/94681110-cb504300-031a-11eb-8f1b-ac8a15641e82.png)

#hacktoberfest
This will require building multiple components to get to the end state, so this issue can be split into multiple PR's. 
The preferred component style usage is Material-UI, but other styling methods are also welcomed.

Please note this does not include integrating with the backend, though that work also is welcomed.

**Comment by Vedant1202** [comment]
Hi, @mukeshmk , I would like to work on this, can you assign this to me? Also, I would like to try out integration with backend once I'm done with UI

**Comment by mukeshmk** [comment]
Hi @Vedant1202 , sure I will assign it to you right away, please comment here occasionally giving me updates about your progress so that I know that you are still working on it. Feel free to raise multiple PRs for the separate features.

**Comment by Vedant1202** [comment]
Thanks. Umm, a small question here, the current UI looks like it occupies only a small fraction of the page, like this
![image](https://user-images.githubusercontent.com/35070972/94792952-5bfc5100-03f7-11eb-91a4-f05fa9aacf32.png)

Do you want it to look somewhat like this?
![image](https://user-images.githubusercontent.com/35070972/94793183-b4cbe980-03f7-11eb-9554-41534e891063.png)


Also, am I free to replace the entire code of the chat page? Or maybe create a new proxy chat page which can then replace the current chat page?

**Comment by mukeshmk** [comment]
@Vedant1202 I want it to look like what you have done, the code which I had is just boilerplate code, so feel free to replace the entire page.

**Comment by mukeshmk** [comment]
Issue resolved in #2, thank you @Vedant1202 for your contributions. Feel free to continue working on this and raising more PR's to improve the application.
